config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: "dashboard#index"

  root to: "players#index"

  resources :friendships

  resources :players do
    resources :player_sessions, only: [ :create ], path: "/sessions"
  end

  get '/players/create_friendship/:id' => 'players#create_friendship'
  get '/players/destroy_friendship/:id' => 'players#destroy_friendship'


end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	
	belongs_to :player
	belongs_to :friend, :class_name => "Player"
end

app/models/player.rb
class Player < ActiveRecord::Base
  	validates_presence_of :name
  	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :i_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :i_friends, :through => :i_friendships, :source => :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include SessionHelper
  before_filter :authenticate_player!
  def index
  end

  private
  def authenticate_player!
    unless player_signed_in?
      redirect_to "/", alert: "You're not signed in"
    end
  end
end

app/controllers/player_sessions_controller.rb
class PlayerSessionsController < ApplicationController
  include SessionHelper
  def create
    if !params[:player_id].blank? && load_player_from_id(params[:player_id])
      session[:current_player_id] = params[:player_id]
    end
    redirect_to request.referer, notice: "Session created!"
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy,:create_friendship]
  respond_to :html, :json

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  def create_friendship
      @friendship = Friendship.new
      @friendship.player_id = session[:current_player_id]
      @friendship.friend_id = @player.id
      @friendship.save
      redirect_to players_url, notice: 'Friendship was successfully created.'
  end

  def destroy_friendship
    @friendship = Friendship.find(params[:id])
    @friendship.destroy    
    redirect_to players_url, notice: 'Friendship was successfully destroyed.'
  end
  
  private
  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
  	def confirm(player)
  		Friendship.where(player_id: session[:current_player_id], friend_id: player).blank?
	end
end 

app/helpers/session_helper.rb
module SessionHelper
  def current_player
    load_player_from_id session[:current_player_id]
  end

  def player_signed_in?
    !!load_player_from_id(session[:current_player_id])
  end

  private
  def load_player_from_id(id)
    Player.find(id) rescue nil
  end
end

app/views/dashboard/index.html.erb
<h1><%= current_player.name %>'s Dashboard</h1>
<ul>

<h2>Players you follow</h2>
	<% current_player.friendships.each do |friends| %>
				<li>
					<%= friends.friend.name %>
        	<%= link_to "Remove Friendship", {:action => 'destroy_friendship',:controller=>"players", :id => friends}, method: :get %> 
				</li>
	<% end %>

</ul>
<ul>
<h2>Players who follow you</h2>


	<% current_player.i_friends.each do |players| %>
    <li>

					<%= players.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueztestFriendship</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= notice %>
    <%= alert %>

    <% if player_signed_in? %>
      Signed in as <%= current_player.name %>
      <br />
    <% end %>

    <ul>
      <li><%= link_to "Dashboard", "/dashboard" %></li>
      <li><%= link_to "Players", "/players" %></li>
    </ul>


    <%= yield %>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>

        <% if confirm(player) &&  player != current_player  %>
          <td><%= link_to "Add friend", {:action => 'create_friendship', :id => player}, method: :get %></td> 
        <% end %>

        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to "Login as #{@player.name}", player_player_sessions_path(@player), method: :post %> |

<%= link_to 'Edit', edit_player_path(@player) %> |

<%= link_to 'Back', players_path %>